###################################################
# Location of the project directory and Makefiles
#
P := .
M := ../../..

###################################################
# Project definition
#
PROJECT_NAME := TutorialMyMakefile
PROJECT_VERSION := 0.1.0
TARGET_NAME := HelloWorld00
TARGET_DESCRIPTION := Hello Word
COMPILATION_MODE := release
BUILD := ../../build

include $(M)/project/Makefile

###################################################
# Compile the project
#
SRC_FILES += src/main.cpp

include $(M)/rules/Makefile